// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ieee-brand-guidelines/BrandAssets.tsx": () => import("../components/mockups/ieee-brand-guidelines/BrandAssets.tsx"),
  "./components/mockups/ieee-brand-guidelines/BrandGuidelines.tsx": () => import("../components/mockups/ieee-brand-guidelines/BrandGuidelines.tsx"),
  "./components/mockups/ieee-brand-guidelines/PosterPatterns.tsx": () => import("../components/mockups/ieee-brand-guidelines/PosterPatterns.tsx")
};
